[package]
name = "rtrace"
version = "0.1.0"
authors = ["me <oreshnikov.ivan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
